# Model config
d_protein: 1152
d_model: 1024
num_heads: 8 # Number of attention heads in cross attention blocks

rllm_dropout: 0.2
gpt_dropout: 0.1

tokenizer_path: "./tokenizer"

# Training Configuration
batch_size: 32
num_epochs: 5
rllm_learning_rate: 3.0e-4
gpt_learning_rate: 5.0e-5
checkpoint_interval: 3000  # Validate and save model every n iterations
plot_interval: 200        # Plot every n iterations

warmup_ratio: 0.05       # warmup steps = warmup_ratio * total_steps
optimizer_weight_decay: 0.01

# Data Paths
data_paths:
  protein_data_path: "./dataset/protein" # path to protein embeddings folder
  pairs_train_path: "./dataset/train.txt"
  pairs_val_path: "./dataset/val.txt"
  pairs_test_path: "./dataset/test.txt"

# Logging
log_path: "./train.log"

# Directories
directories:
  checkpoint_dir: "./checkpoints"
  plots_dir: "./plots"
